tap "stripe/stripe-cli"

brew "actionlint"
brew "argo"
brew "awscli"
brew "ffmpeg"
brew "gh"
brew "git"
brew "helm"
brew "heroku"
brew "java"
brew "kubectl"
brew "libpq"
brew "libyaml"
brew "mailhog"
brew "mas"
brew "mise"
brew "openssl"
brew "pandoc"
brew "postgresql@18"
brew "rg"
brew "shellcheck"
brew "stripe"
brew "yarn"
brew "yt-dlp"
brew "vips"

cask "adobe-digital-editions"
cask "avg-antivirus"
cask "basictex"
cask "calibre"
cask "cleanshot"
cask "cyberduck"
cask "deckset"
cask "fork"
cask "jdownloader"
cask "google-chrome"
cask "kobo"
cask "nordvpn"
cask "pop-app"
cask "vlc"
cask "whatsapp"
cask "zed"

mas "Things", id: 904280696
