tap "heroku/brew"
tap "homebrew/autoupdate"

brew "age"
brew "awscli"
brew "fd"
brew "ffmpeg"
brew "glow"
brew "heroku"
brew "isync"
brew "java"
brew "jq"
brew "mas"
brew "msmtp"
brew "neomutt"
brew "netlify-cli"
brew "oauth2c"
brew "pass"
brew "portaudio"
brew "trash"
brew "tree"
brew "youtube-dl"
brew "z80asm"

cask "1password"
cask "adobe-digital-editions"
cask "audacity"
cask "brave-browser"
cask "burp-suite"
cask "calibre"
cask "deckset"
cask "discord"
cask "docker"
cask "doxie"
cask "dropbox"
cask "firefox"
cask "fork"
cask "google-chrome"
cask "google-drive"
cask "inkscape"
cask "kdiff3"
cask "keybase"
cask "kobo"
cask "losslesscut"
cask "microsoft-teams"
cask "pop"
cask "qlmarkdown"
cask "quicklook-json"
cask "retro-virtual-machine"
cask "slack"
cask "stats"
cask "spotify"
cask "telegram"
cask "now-tv-player"
cask "tuple"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"

# mas "Things", id: 904280696
# mas "Seashore", id: 1448648921

