#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
  puts file
  next if file =~ /install|README/
  target = File.join(home, ".#{file}")
  command = "ln -fs #{File.expand_path file} #{target}"
  puts command
  system(command)
end
